name: Uwuify
version: '${project.version}'
main: ml.treecaptcha.uwuify.spigot.Uwuify
api-version: 1.19
authors: [ TreeCaptcha ]
description: made with stolen code from Ran-helo/uwu
website: http://treecaptcha.ml/
softdepend: [ DiscordSRV ]

commands:
  toggleuwu:
    description: Toggles uwuification
    usage: /toggleuwu
    permission: uwuify.toggle